project_id = "vbabuyyvgltbleinopkn"

[functions.generate-report]
verify_jwt = true

[functions.setup-tuition-admin]
verify_jwt = false

[functions.create-student-user]
verify_jwt = true

[functions.backup-tuition-data]
verify_jwt = true

[functions.check-subscription-reminders]
verify_jwt = false

[functions.send-attendance-reminders]
verify_jwt = false
